-- Generated by pgxsinkit-generate
-- Re-run after any registry change.

CREATE OR REPLACE FUNCTION "pgxsinkit_apply_mutations"(
  p_batch jsonb,
  p_request_path text,
  p_log_enabled boolean,
  p_rls_enabled boolean,
  p_user_claims jsonb
) RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  mutation jsonb;
  dml_sql text;
  v_table text;
  v_kind text;
  v_payload jsonb;
  v_entity_key jsonb;
  v_mutation_id text;
  v_mutation_seq integer;
  v_client_timestamp_us bigint;
  _claims jsonb;
  _target_role text;
  _previous_role text;
  _previous_claims text;
  _previous_claim_sub text;
BEGIN
  IF p_rls_enabled THEN
    -- Capture the caller's role/claims before switching into the RLS actor context, so the
    -- batch does not leak that context into the rest of the caller's transaction. The HTTP
    -- route RESET ROLEs after calling this function, but in-transaction callers cannot —
    -- restoring here leaves every caller exactly as it was found.
    _previous_role := current_setting('role', true);
    _previous_claims := current_setting('request.jwt.claims', true);
    _previous_claim_sub := current_setting('request.jwt.claim.sub', true);
    _claims := COALESCE(p_user_claims, '{}'::jsonb);
    _target_role := COALESCE(NULLIF(_claims ->> 'role', ''), 'authenticated');
    BEGIN
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = _target_role) THEN
        PERFORM set_config('role', _target_role, true);
      ELSIF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        PERFORM set_config('role', 'authenticated', true);
      END IF;
    EXCEPTION WHEN insufficient_privilege THEN NULL;
    END;
    PERFORM set_config('request.jwt.claims', _claims::text, true);
    IF _claims ? 'sub' THEN
      PERFORM set_config('request.jwt.claim.sub', _claims ->> 'sub', true);
    END IF;
  END IF;

  IF jsonb_typeof(p_batch) <> 'object' THEN
    RAISE EXCEPTION 'Batch payload must be a JSON object';
  END IF;

  IF jsonb_typeof(p_batch->'mutations') <> 'array' THEN
    RAISE EXCEPTION 'Batch payload mutations must be a JSON array';
  END IF;

  FOR mutation IN SELECT value FROM jsonb_array_elements(p_batch->'mutations')
  LOOP
    dml_sql := NULL;
    v_table := mutation->>'tableName';
    v_kind := mutation->>'kind';
    v_payload := COALESCE(mutation->'payload', '{}'::jsonb);
    v_entity_key := COALESCE(mutation->'entityKey', '{}'::jsonb);
    v_mutation_id := mutation->>'mutationId';
    v_mutation_seq := (mutation->>'mutationSeq')::integer;
    v_client_timestamp_us := NULLIF(mutation->>'clientTimestampUs', '')::bigint;

    IF FALSE THEN
      NULL;
    ELSIF v_table = 'authors' THEN
        IF v_kind = 'create' THEN
          SELECT format(
          'INSERT INTO "authors" (%s) VALUES (%s)',
          concat_ws(', ', nullif(string_agg(quote_ident(col_name), ', '), ''), '"owner_id", "modified_by", "created_at_us", "updated_at_us"'),
          concat_ws(', ', nullif(string_agg(format('($1->>%L)::%s', col_name, col_type), ', '), ''), 'auth.uid(), auth.uid(), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)')
        )
        INTO dml_sql
        FROM (VALUES
            ('id', 'uuid'),
            ('name', 'varchar(120)')
        ) AS col_types(col_name, col_type)
        WHERE v_payload ? col_name;

        IF dml_sql IS NOT NULL THEN
          EXECUTE dml_sql USING v_payload;
        END IF;
        ELSIF v_kind = 'update' THEN
          SELECT format(
          'UPDATE "authors" SET %s WHERE "id" = ($2->>%L)::uuid',
          concat_ws(', ', nullif(string_agg(format('%I = ($1->>%L)::%s', col_name, col_name, col_type), ', '), ''), '"modified_by" = auth.uid(), "updated_at_us" = CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)'),
          'id'
        )
        INTO dml_sql
        FROM (VALUES
            ('name', 'varchar(120)'),
            ('owner_id', 'uuid'),
            ('created_at_us', 'bigint')
        ) AS col_types(col_name, col_type)
        WHERE v_payload ? col_name;

        IF dml_sql IS NOT NULL THEN
          EXECUTE dml_sql USING v_payload, v_entity_key;
        END IF;
        ELSIF v_kind = 'delete' THEN
          DELETE FROM "authors"
        WHERE "id" = (v_entity_key->>'id')::uuid;
        ELSE
          RAISE EXCEPTION 'Unsupported mutation kind "%" for table "%"', v_kind, v_table;
        END IF;
ELSIF v_table = 'todos' THEN
        IF v_kind = 'create' THEN
          SELECT format(
          'INSERT INTO "todos" (%s) VALUES (%s)',
          concat_ws(', ', nullif(string_agg(quote_ident(col_name), ', '), ''), '"owner_id", "modified_by", "created_at_us", "updated_at_us"'),
          concat_ws(', ', nullif(string_agg(format('($1->>%L)::%s', col_name, col_type), ', '), ''), 'auth.uid(), auth.uid(), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)')
        )
        INTO dml_sql
        FROM (VALUES
            ('id', 'uuid'),
            ('title', 'varchar(120)'),
            ('description', 'varchar(4000)'),
            ('author_id', 'uuid'),
            ('status', 'todo_status'),
            ('priority', 'todo_priority')
        ) AS col_types(col_name, col_type)
        WHERE v_payload ? col_name;

        IF dml_sql IS NOT NULL THEN
          EXECUTE dml_sql USING v_payload;
        END IF;
        ELSIF v_kind = 'update' THEN
          SELECT format(
          'UPDATE "todos" SET %s WHERE "id" = ($2->>%L)::uuid',
          concat_ws(', ', nullif(string_agg(format('%I = ($1->>%L)::%s', col_name, col_name, col_type), ', '), ''), '"modified_by" = auth.uid(), "updated_at_us" = CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)'),
          'id'
        )
        INTO dml_sql
        FROM (VALUES
            ('title', 'varchar(120)'),
            ('description', 'varchar(4000)'),
            ('author_id', 'uuid'),
            ('owner_id', 'uuid'),
            ('status', 'todo_status'),
            ('priority', 'todo_priority'),
            ('created_at_us', 'bigint')
        ) AS col_types(col_name, col_type)
        WHERE v_payload ? col_name;

        IF dml_sql IS NOT NULL THEN
          EXECUTE dml_sql USING v_payload, v_entity_key;
        END IF;
        ELSIF v_kind = 'delete' THEN
          DELETE FROM "todos"
        WHERE "id" = (v_entity_key->>'id')::uuid;
        ELSE
          RAISE EXCEPTION 'Unsupported mutation kind "%" for table "%"', v_kind, v_table;
        END IF;
    ELSE
      RAISE EXCEPTION 'Unknown table "%" in batch mutation', v_table;
    END IF;

    IF p_log_enabled THEN
      INSERT INTO operations_log (
        table_name,
        operation_kind,
        entity_key_json,
        payload_json,
        status,
        http_status,
        mutation_id,
        mutation_seq,
        client_timestamp_us,
        request_path,
        server_timestamp_us
      ) VALUES (
        v_table,
        v_kind,
        v_entity_key,
        v_payload,
        'succeeded',
        200,
        v_mutation_id::uuid,
        v_mutation_seq,
        v_client_timestamp_us,
        p_request_path,
        CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)
      );
    END IF;
  END LOOP;

  IF p_rls_enabled THEN
    -- Restore the caller's prior role/claims captured above, so the RLS context applied for
    -- the batch does not persist into subsequent statements of the caller's transaction.
    BEGIN
      PERFORM set_config('role', COALESCE(NULLIF(_previous_role, ''), 'none'), true);
    EXCEPTION WHEN insufficient_privilege THEN NULL;
    END;
    PERFORM set_config('request.jwt.claims', COALESCE(_previous_claims, ''), true);
    PERFORM set_config('request.jwt.claim.sub', COALESCE(_previous_claim_sub, ''), true);
  END IF;
END;
$$;
