-- Generated by scripts/generate-governance-migration.ts
-- Registry source: packages/demo/src/registry.ts

-- Source: governance.auth.schema
CREATE SCHEMA IF NOT EXISTS auth;
--> statement-breakpoint
-- Source: governance.auth.role_authenticated
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    BEGIN
      CREATE ROLE authenticated NOLOGIN;
    EXCEPTION
      WHEN insufficient_privilege THEN
        NULL;
    END;
  END IF;
END;
$$;
--> statement-breakpoint
-- Source: governance.auth.set_auth_context
CREATE OR REPLACE FUNCTION auth.set_auth_context(claims jsonb)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  normalized_claims jsonb := COALESCE(claims, '{}'::jsonb);
  target_role text := COALESCE(NULLIF(normalized_claims ->> 'role', ''), 'authenticated');
BEGIN
  BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = target_role) THEN
      PERFORM set_config('role', target_role, true);
    ELSIF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
      PERFORM set_config('role', 'authenticated', true);
    END IF;
  EXCEPTION
    WHEN insufficient_privilege THEN
      NULL;
  END;
  PERFORM set_config('request.jwt.claims', normalized_claims::text, true);

  IF normalized_claims ? 'sub' THEN
    PERFORM set_config('request.jwt.claim.sub', normalized_claims ->> 'sub', true);
  END IF;
END;
$$;
--> statement-breakpoint
-- Source: governance.auth.uid
CREATE OR REPLACE FUNCTION auth.uid()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT coalesce(nullif(current_setting('request.jwt.claim.sub', true), ''), (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub'))::uuid
$$;
--> statement-breakpoint
-- Source: governance.auth.jwt
CREATE OR REPLACE FUNCTION auth.jwt()
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
  SELECT coalesce(nullif(current_setting('request.jwt.claim', true), ''), nullif(current_setting('request.jwt.claims', true), ''))::jsonb
$$;
--> statement-breakpoint
-- Source: governance.auth.has_role
CREATE OR REPLACE FUNCTION auth.has_role(role_name text)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM jsonb_array_elements_text(COALESCE(auth.jwt() -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS assigned_role(role_name_value)
    WHERE assigned_role.role_name_value = role_name
  )
$$;
--> statement-breakpoint
-- Source: governance.auth.grants.authenticated
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA auth TO authenticated';
    EXECUTE 'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA auth TO authenticated';
  END IF;
END;
$$;
--> statement-breakpoint
-- Source: registry.authors.governance.rls.enabled
ALTER TABLE "authors" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
-- Source: registry.authors.governance.rls.grants.authenticated
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "authors" TO authenticated';
  END IF;
END;
$$;
--> statement-breakpoint
-- Source: registry.authors.governance.rls.policy.authors_select_owner_or_admin
DROP POLICY IF EXISTS "authors_select_owner_or_admin" ON "authors";
CREATE POLICY "authors_select_owner_or_admin" ON "authors"
AS PERMISSIVE
FOR SELECT
TO "authenticated" USING (owner_id = auth.uid() OR auth.has_role('admin'));
--> statement-breakpoint
-- Source: registry.authors.governance.rls.policy.authors_insert_owner_or_admin
DROP POLICY IF EXISTS "authors_insert_owner_or_admin" ON "authors";
CREATE POLICY "authors_insert_owner_or_admin" ON "authors"
AS PERMISSIVE
FOR INSERT
TO "authenticated" WITH CHECK (owner_id = auth.uid() OR auth.has_role('admin'));
--> statement-breakpoint
-- Source: registry.authors.governance.rls.policy.authors_update_owner_or_admin
DROP POLICY IF EXISTS "authors_update_owner_or_admin" ON "authors";
CREATE POLICY "authors_update_owner_or_admin" ON "authors"
AS PERMISSIVE
FOR UPDATE
TO "authenticated" USING (owner_id = auth.uid() OR auth.has_role('admin')) WITH CHECK (owner_id = auth.uid() OR auth.has_role('admin'));
--> statement-breakpoint
-- Source: registry.authors.governance.rls.policy.authors_delete_owner_or_admin
DROP POLICY IF EXISTS "authors_delete_owner_or_admin" ON "authors";
CREATE POLICY "authors_delete_owner_or_admin" ON "authors"
AS PERMISSIVE
FOR DELETE
TO "authenticated" USING (owner_id = auth.uid() OR auth.has_role('admin'));
--> statement-breakpoint
-- Source: registry.todos.governance.deferrableConstraints.todos_author_id_authors_id_fkey
ALTER TABLE "todos"
ALTER CONSTRAINT "todos_author_id_authors_id_fkey"
DEFERRABLE INITIALLY IMMEDIATE;
--> statement-breakpoint
-- Source: registry.todos.governance.rls.enabled
ALTER TABLE "todos" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
-- Source: registry.todos.governance.rls.grants.authenticated
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "todos" TO authenticated';
  END IF;
END;
$$;
--> statement-breakpoint
-- Source: registry.todos.governance.rls.policy.todos_select_owner_or_admin
DROP POLICY IF EXISTS "todos_select_owner_or_admin" ON "todos";
CREATE POLICY "todos_select_owner_or_admin" ON "todos"
AS PERMISSIVE
FOR SELECT
TO "authenticated" USING (owner_id = auth.uid() OR auth.has_role('admin'));
--> statement-breakpoint
-- Source: registry.todos.governance.rls.policy.todos_insert_owner_or_admin
DROP POLICY IF EXISTS "todos_insert_owner_or_admin" ON "todos";
CREATE POLICY "todos_insert_owner_or_admin" ON "todos"
AS PERMISSIVE
FOR INSERT
TO "authenticated" WITH CHECK (owner_id = auth.uid() OR auth.has_role('admin'));
--> statement-breakpoint
-- Source: registry.todos.governance.rls.policy.todos_update_owner_or_admin
DROP POLICY IF EXISTS "todos_update_owner_or_admin" ON "todos";
CREATE POLICY "todos_update_owner_or_admin" ON "todos"
AS PERMISSIVE
FOR UPDATE
TO "authenticated" USING (owner_id = auth.uid() OR auth.has_role('admin')) WITH CHECK (owner_id = auth.uid() OR auth.has_role('admin'));
--> statement-breakpoint
-- Source: registry.todos.governance.rls.policy.todos_delete_owner_or_admin
DROP POLICY IF EXISTS "todos_delete_owner_or_admin" ON "todos";
CREATE POLICY "todos_delete_owner_or_admin" ON "todos"
AS PERMISSIVE
FOR DELETE
TO "authenticated" USING (owner_id = auth.uid() OR auth.has_role('admin'));
