-- Generated by pgxsinkit-generate --utilities
-- Installs the canonical pgxsinkit_clock_us() microsecond clock. MUST be the first folder in the chain.

-- The pgxsinkit canonical microsecond clock. Deliberately clock_timestamp() (advances WITHIN a
-- transaction — LWW/audit ordering of multi-row applies depends on it), never now()/transaction_timestamp()
-- (frozen at tx start). FLOOR + BIGINT: whole microseconds since epoch.
CREATE OR REPLACE FUNCTION public.pgxsinkit_clock_us()
  RETURNS bigint
  LANGUAGE sql
  VOLATILE
AS $$
  SELECT CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)
$$;
