-- Generated by scripts/generate-governance-migration.ts
-- Re-run after registry governance changes.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "authors" TO "authenticated"';
  END IF;
END;
$$;

ALTER TABLE "todos" ALTER CONSTRAINT "todos_author_id_authors_id_fkey" DEFERRABLE INITIALLY IMMEDIATE;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "todos" TO "authenticated"';
  END IF;
END;
$$;

ALTER TABLE "fk_children" ALTER CONSTRAINT "fk_children_parent_fk" DEFERRABLE INITIALLY IMMEDIATE;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "rls_todos" TO "authenticated"';
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "work_items" TO "authenticated"';
  END IF;
END;
$$;
