-- Generated by pgxsinkit-generate
-- Re-run after any registry change.

-- ADR-0015: the function now RETURNS the per-mutation conflicts (a reject-if-stale stale write). A
-- return-type change cannot be a bare CREATE OR REPLACE, so drop the prior (void-returning) signature
-- first. Idempotent: re-running installs the same definition.
DROP FUNCTION IF EXISTS "pgxsinkit_apply_mutations"(jsonb, text, boolean, boolean, jsonb);

CREATE OR REPLACE FUNCTION "pgxsinkit_apply_mutations"(
  p_batch jsonb,
  p_request_path text,
  p_log_enabled boolean,
  p_rls_enabled boolean,
  p_user_claims jsonb
) RETURNS TABLE(mutation_id uuid, table_name text, current_server_version bigint) LANGUAGE plpgsql AS $$
DECLARE
  dml_sql text;
  v_table text;
  v_kind text;
  v_sig text;
  v_rows jsonb;
  v_cols text;
  v_vals text;
  v_set text;
  -- ADR-0015: stale-write conflicts collected across the batch (mutationId + the row's current
  -- Server version), returned to the handler which turns them into 'conflicted' acks.
  v_conflicts jsonb := '[]'::jsonb;
  v_group_conflicts jsonb;
  _claims jsonb;
  _target_role text;
  _previous_role text;
  _previous_claims text;
  _previous_claim_sub text;
BEGIN
  IF p_rls_enabled THEN
    -- Capture the caller's role/claims before switching into the RLS actor context, so the
    -- batch does not leak that context into the rest of the caller's transaction. The HTTP
    -- route RESET ROLEs after calling this function, but in-transaction callers cannot —
    -- restoring here leaves every caller exactly as it was found.
    _previous_role := current_setting('role', true);
    _previous_claims := current_setting('request.jwt.claims', true);
    _previous_claim_sub := current_setting('request.jwt.claim.sub', true);
    _claims := COALESCE(p_user_claims, '{}'::jsonb);
    _target_role := COALESCE(NULLIF(_claims ->> 'role', ''), 'authenticated');
    BEGIN
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = _target_role) THEN
        PERFORM set_config('role', _target_role, true);
      ELSIF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        PERFORM set_config('role', 'authenticated', true);
      END IF;
    EXCEPTION WHEN insufficient_privilege THEN NULL;
    END;
    PERFORM set_config('request.jwt.claims', _claims::text, true);
    IF _claims ? 'sub' THEN
      PERFORM set_config('request.jwt.claim.sub', _claims ->> 'sub', true);
    END IF;
  END IF;

  IF jsonb_typeof(p_batch) <> 'object' THEN
    RAISE EXCEPTION 'Batch payload must be a JSON object';
  END IF;

  IF jsonb_typeof(p_batch->'mutations') <> 'array' THEN
    RAISE EXCEPTION 'Batch payload mutations must be a JSON array';
  END IF;

  -- Group the batch by (table, kind, payload column-set) and apply each group with one statement
  -- (ADR-0014 Phase 4). Groups run in ascending min(mutationSeq) so submission order is preserved
  -- across tables (FK-safe; the batch transaction also runs SET CONSTRAINTS ALL DEFERRED).
  FOR v_table, v_kind, v_sig, v_rows IN
    SELECT
      grouped.table_name,
      grouped.kind,
      grouped.sig,
      jsonb_agg(grouped.mutation ORDER BY grouped.mutation_seq)
    FROM (
      SELECT
        m->>'tableName' AS table_name,
        m->>'kind' AS kind,
        COALESCE((
          SELECT string_agg(payload_key, ',' ORDER BY payload_key)
          FROM jsonb_object_keys(COALESCE(m->'payload', '{}'::jsonb)) AS payload_key
        ), '') AS sig,
        m AS mutation,
        (m->>'mutationSeq')::integer AS mutation_seq
      FROM jsonb_array_elements(p_batch->'mutations') AS m
    ) AS grouped
    GROUP BY grouped.table_name, grouped.kind, grouped.sig
    ORDER BY MIN(grouped.mutation_seq)
  LOOP
    dml_sql := NULL;
    v_cols := NULL;
    v_vals := NULL;
    v_set := NULL;

    IF FALSE THEN
      NULL;
    ELSIF v_table = 'profile' THEN
        IF v_kind = 'create' THEN
          SELECT
          string_agg(quote_ident(col_name), ', ' ORDER BY col_name),
          string_agg(format('(x.p->>%L)::%s', col_name, col_type), ', ' ORDER BY col_name)
        INTO v_cols, v_vals
        FROM (VALUES
            ('id', 'uuid'),
            ('display_name', 'varchar(120)'),
            ('avatar_color', 'varchar(24)')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        dml_sql := format(
          'INSERT INTO "profile" (%s) SELECT %s FROM jsonb_to_recordset($1) AS x(p jsonb)',
          concat_ws(', ', nullif(v_cols, ''), NULL),
          concat_ws(', ', nullif(v_vals, ''), NULL)
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb))), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'update' THEN
          SELECT string_agg(format('%I = (x.p->>%L)::%s', col_name, col_name, col_type), ', ' ORDER BY col_name)
        INTO v_set
        FROM (VALUES
            ('display_name', 'varchar(120)'),
            ('avatar_color', 'varchar(24)')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        dml_sql := format(
          'UPDATE "profile" AS t SET %s FROM jsonb_to_recordset($1) AS x(p jsonb, k jsonb) WHERE t."id" = (x.k->>''id'')::uuid',
          concat_ws(', ', nullif(v_set, ''), NULL)
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb), 'k', COALESCE(elem->'entityKey', '{}'::jsonb))), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'delete' THEN
          EXECUTE 'DELETE FROM "profile" AS t USING jsonb_to_recordset($1) AS x("id" uuid) WHERE t."id" = x."id"' USING (
          SELECT COALESCE(jsonb_agg(elem->'entityKey'), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSE
          RAISE EXCEPTION 'Unsupported mutation kind "%" for table "%"', v_kind, v_table;
        END IF;
ELSIF v_table = 'team' THEN
        IF v_kind = 'create' THEN
          SELECT
          string_agg(quote_ident(col_name), ', ' ORDER BY col_name),
          string_agg(format('(x.p->>%L)::%s', col_name, col_type), ', ' ORDER BY col_name)
        INTO v_cols, v_vals
        FROM (VALUES
            ('id', 'uuid'),
            ('name', 'varchar(120)'),
            ('created_at_us', 'bigint')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        dml_sql := format(
          'INSERT INTO "team" (%s) SELECT %s FROM jsonb_to_recordset($1) AS x(p jsonb)',
          concat_ws(', ', nullif(v_cols, ''), NULL),
          concat_ws(', ', nullif(v_vals, ''), NULL)
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb))), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'update' THEN
          SELECT string_agg(format('%I = (x.p->>%L)::%s', col_name, col_name, col_type), ', ' ORDER BY col_name)
        INTO v_set
        FROM (VALUES
            ('name', 'varchar(120)'),
            ('created_at_us', 'bigint')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        dml_sql := format(
          'UPDATE "team" AS t SET %s FROM jsonb_to_recordset($1) AS x(p jsonb, k jsonb) WHERE t."id" = (x.k->>''id'')::uuid',
          concat_ws(', ', nullif(v_set, ''), NULL)
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb), 'k', COALESCE(elem->'entityKey', '{}'::jsonb))), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'delete' THEN
          EXECUTE 'DELETE FROM "team" AS t USING jsonb_to_recordset($1) AS x("id" uuid) WHERE t."id" = x."id"' USING (
          SELECT COALESCE(jsonb_agg(elem->'entityKey'), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSE
          RAISE EXCEPTION 'Unsupported mutation kind "%" for table "%"', v_kind, v_table;
        END IF;
ELSIF v_table = 'team_member' THEN
        IF v_kind = 'create' THEN
          SELECT
          string_agg(quote_ident(col_name), ', ' ORDER BY col_name),
          string_agg(format('(x.p->>%L)::%s', col_name, col_type), ', ' ORDER BY col_name)
        INTO v_cols, v_vals
        FROM (VALUES
            ('id', 'uuid'),
            ('team_id', 'uuid'),
            ('user_id', 'uuid')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        dml_sql := format(
          'INSERT INTO "team_member" (%s) SELECT %s FROM jsonb_to_recordset($1) AS x(p jsonb)',
          concat_ws(', ', nullif(v_cols, ''), '"created_at_us", "updated_at_us"'),
          concat_ws(', ', nullif(v_vals, ''), 'CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)')
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb))), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'update' THEN
          SELECT string_agg(format('%I = (x.p->>%L)::%s', col_name, col_name, col_type), ', ' ORDER BY col_name)
        INTO v_set
        FROM (VALUES
            ('team_id', 'uuid'),
            ('user_id', 'uuid'),
            ('created_at_us', 'bigint')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        dml_sql := format(
          'UPDATE "team_member" AS t SET %s FROM jsonb_to_recordset($1) AS x(p jsonb, k jsonb) WHERE t."id" = (x.k->>''id'')::uuid',
          concat_ws(', ', nullif(v_set, ''), '"updated_at_us" = GREATEST(CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT), "updated_at_us" + 1)')
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb), 'k', COALESCE(elem->'entityKey', '{}'::jsonb))), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'delete' THEN
          EXECUTE 'DELETE FROM "team_member" AS t USING jsonb_to_recordset($1) AS x("id" uuid) WHERE t."id" = x."id"' USING (
          SELECT COALESCE(jsonb_agg(elem->'entityKey'), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSE
          RAISE EXCEPTION 'Unsupported mutation kind "%" for table "%"', v_kind, v_table;
        END IF;
ELSIF v_table = 'channel' THEN
        IF v_kind = 'create' THEN
          SELECT
          string_agg(quote_ident(col_name), ', ' ORDER BY col_name),
          string_agg(format('(x.p->>%L)::%s', col_name, col_type), ', ' ORDER BY col_name)
        INTO v_cols, v_vals
        FROM (VALUES
            ('id', 'uuid'),
            ('team_id', 'uuid'),
            ('kind', 'channel_kind'),
            ('name', 'varchar(120)'),
            ('created_at_us', 'bigint')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        dml_sql := format(
          'INSERT INTO "channel" (%s) SELECT %s FROM jsonb_to_recordset($1) AS x(p jsonb)',
          concat_ws(', ', nullif(v_cols, ''), NULL),
          concat_ws(', ', nullif(v_vals, ''), NULL)
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb))), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'update' THEN
          SELECT string_agg(format('%I = (x.p->>%L)::%s', col_name, col_name, col_type), ', ' ORDER BY col_name)
        INTO v_set
        FROM (VALUES
            ('team_id', 'uuid'),
            ('kind', 'channel_kind'),
            ('name', 'varchar(120)'),
            ('created_at_us', 'bigint')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        dml_sql := format(
          'UPDATE "channel" AS t SET %s FROM jsonb_to_recordset($1) AS x(p jsonb, k jsonb) WHERE t."id" = (x.k->>''id'')::uuid',
          concat_ws(', ', nullif(v_set, ''), NULL)
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb), 'k', COALESCE(elem->'entityKey', '{}'::jsonb))), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'delete' THEN
          EXECUTE 'DELETE FROM "channel" AS t USING jsonb_to_recordset($1) AS x("id" uuid) WHERE t."id" = x."id"' USING (
          SELECT COALESCE(jsonb_agg(elem->'entityKey'), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSE
          RAISE EXCEPTION 'Unsupported mutation kind "%" for table "%"', v_kind, v_table;
        END IF;
ELSIF v_table = 'issue' THEN
        IF v_kind = 'create' THEN
          SELECT
          string_agg(quote_ident(col_name), ', ' ORDER BY col_name),
          string_agg(format('(x.p->>%L)::%s', col_name, col_type), ', ' ORDER BY col_name)
        INTO v_cols, v_vals
        FROM (VALUES
            ('id', 'uuid'),
            ('team_id', 'uuid'),
            ('assignee_id', 'uuid'),
            ('title', 'varchar(200)'),
            ('description', 'varchar(4000)'),
            ('status', 'issue_status'),
            ('priority', 'issue_priority')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        dml_sql := format(
          'INSERT INTO "issue" (%s) SELECT %s FROM jsonb_to_recordset($1) AS x(p jsonb)',
          concat_ws(', ', nullif(v_cols, ''), '"created_by", "created_at_us", "updated_at_us"'),
          concat_ws(', ', nullif(v_vals, ''), 'auth.uid(), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)')
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb))), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'update' THEN
          SELECT string_agg(format('%I = (x.p->>%L)::%s', col_name, col_name, col_type), ', ' ORDER BY col_name)
        INTO v_set
        FROM (VALUES
            ('team_id', 'uuid'),
            ('assignee_id', 'uuid'),
            ('title', 'varchar(200)'),
            ('description', 'varchar(4000)'),
            ('status', 'issue_status'),
            ('priority', 'issue_priority'),
            ('created_by', 'uuid'),
            ('created_at_us', 'bigint')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        EXECUTE 'SELECT COALESCE(jsonb_agg(jsonb_build_object(''mutationId'', x.m, ''tableName'', ''issue'', ''currentServerVersion'', t."updated_at_us")), ''[]''::jsonb) FROM jsonb_to_recordset($1) AS x(p jsonb, k jsonb, b bigint, m uuid) LEFT JOIN "issue" AS t ON t."id" = (x.k->>''id'')::uuid WHERE t."id" IS NULL OR (x.b IS NOT NULL AND t."updated_at_us" > x.b)'
          INTO v_group_conflicts
          USING (
            SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb), 'k', COALESCE(elem->'entityKey', '{}'::jsonb), 'b', (elem->>'baseServerVersion')::bigint, 'm', elem->>'mutationId')), '[]'::jsonb)
            FROM jsonb_array_elements(v_rows) AS elem
          );
        v_conflicts := v_conflicts || v_group_conflicts;

        dml_sql := format(
          'UPDATE "issue" AS t SET %s FROM jsonb_to_recordset($1) AS x(p jsonb, k jsonb, b bigint, m uuid) WHERE t."id" = (x.k->>''id'')::uuid AND (x.b IS NULL OR t."updated_at_us" <= x.b)',
          concat_ws(', ', nullif(v_set, ''), '"updated_at_us" = GREATEST(CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT), "updated_at_us" + 1)')
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb), 'k', COALESCE(elem->'entityKey', '{}'::jsonb), 'b', (elem->>'baseServerVersion')::bigint, 'm', elem->>'mutationId')), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'delete' THEN
          EXECUTE 'SELECT COALESCE(jsonb_agg(jsonb_build_object(''mutationId'', x.m, ''tableName'', ''issue'', ''currentServerVersion'', t."updated_at_us")), ''[]''::jsonb) FROM jsonb_to_recordset($1) AS x("id" uuid, b bigint, m uuid) JOIN "issue" AS t ON t."id" = x."id" WHERE x.b IS NOT NULL AND t."updated_at_us" > x.b'
          INTO v_group_conflicts
          USING (
            SELECT COALESCE(jsonb_agg(COALESCE(elem->'entityKey', '{}'::jsonb) || jsonb_build_object('b', (elem->>'baseServerVersion')::bigint, 'm', elem->>'mutationId')), '[]'::jsonb)
            FROM jsonb_array_elements(v_rows) AS elem
          );
        v_conflicts := v_conflicts || v_group_conflicts;

        EXECUTE 'DELETE FROM "issue" AS t USING jsonb_to_recordset($1) AS x("id" uuid, b bigint, m uuid) WHERE t."id" = x."id" AND (x.b IS NULL OR t."updated_at_us" <= x.b)' USING (
          SELECT COALESCE(jsonb_agg(COALESCE(elem->'entityKey', '{}'::jsonb) || jsonb_build_object('b', (elem->>'baseServerVersion')::bigint, 'm', elem->>'mutationId')), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSE
          RAISE EXCEPTION 'Unsupported mutation kind "%" for table "%"', v_kind, v_table;
        END IF;
ELSIF v_table = 'message' THEN
        IF v_kind = 'create' THEN
          SELECT
          string_agg(quote_ident(col_name), ', ' ORDER BY col_name),
          string_agg(format('(x.p->>%L)::%s', col_name, col_type), ', ' ORDER BY col_name)
        INTO v_cols, v_vals
        FROM (VALUES
            ('id', 'uuid'),
            ('channel_id', 'uuid'),
            ('body', 'varchar(4000)')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        dml_sql := format(
          'INSERT INTO "message" (%s) SELECT %s FROM jsonb_to_recordset($1) AS x(p jsonb)',
          concat_ws(', ', nullif(v_cols, ''), '"author_id", "created_at_us", "updated_at_us"'),
          concat_ws(', ', nullif(v_vals, ''), 'auth.uid(), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)')
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb))), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'update' THEN
          SELECT string_agg(format('%I = (x.p->>%L)::%s', col_name, col_name, col_type), ', ' ORDER BY col_name)
        INTO v_set
        FROM (VALUES
            ('channel_id', 'uuid'),
            ('author_id', 'uuid'),
            ('body', 'varchar(4000)'),
            ('created_at_us', 'bigint')
        ) AS col_types(col_name, col_type)
        WHERE col_name = ANY(string_to_array(v_sig, ','));

        dml_sql := format(
          'UPDATE "message" AS t SET %s FROM jsonb_to_recordset($1) AS x(p jsonb, k jsonb) WHERE t."id" = (x.k->>''id'')::uuid',
          concat_ws(', ', nullif(v_set, ''), '"updated_at_us" = GREATEST(CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT), "updated_at_us" + 1)')
        );
        EXECUTE dml_sql USING (
          SELECT COALESCE(jsonb_agg(jsonb_build_object('p', COALESCE(elem->'payload', '{}'::jsonb), 'k', COALESCE(elem->'entityKey', '{}'::jsonb))), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSIF v_kind = 'delete' THEN
          EXECUTE 'DELETE FROM "message" AS t USING jsonb_to_recordset($1) AS x("id" uuid) WHERE t."id" = x."id"' USING (
          SELECT COALESCE(jsonb_agg(elem->'entityKey'), '[]'::jsonb)
          FROM jsonb_array_elements(v_rows) AS elem
        );
        ELSE
          RAISE EXCEPTION 'Unsupported mutation kind "%" for table "%"', v_kind, v_table;
        END IF;
    ELSE
      RAISE EXCEPTION 'Unknown table "%" in batch mutation', v_table;
    END IF;
  END LOOP;

  IF p_log_enabled THEN
    -- One batched log insert (the whole batch is a single transaction, so a per-mutation loop
    -- bought nothing): a runtime apply failure above rolls the whole transaction back, log rows
    -- included, preserving the existing whole-batch-failure semantics.
    INSERT INTO operations_log (
      table_name,
      operation_kind,
      entity_key_json,
      payload_json,
      status,
      http_status,
      mutation_id,
      mutation_seq,
      client_timestamp_us,
      request_path,
      server_timestamp_us
    )
    SELECT
      m->>'tableName',
      m->>'kind',
      COALESCE(m->'entityKey', '{}'::jsonb),
      COALESCE(m->'payload', '{}'::jsonb),
      'succeeded',
      200,
      (m->>'mutationId')::uuid,
      (m->>'mutationSeq')::integer,
      NULLIF(m->>'clientTimestampUs', '')::bigint,
      p_request_path,
      CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)
    FROM jsonb_array_elements(p_batch->'mutations') AS m;
  END IF;

  IF p_rls_enabled THEN
    -- Restore the caller's prior role/claims captured above, so the RLS context applied for
    -- the batch does not persist into subsequent statements of the caller's transaction.
    BEGIN
      PERFORM set_config('role', COALESCE(NULLIF(_previous_role, ''), 'none'), true);
    EXCEPTION WHEN insufficient_privilege THEN NULL;
    END;
    PERFORM set_config('request.jwt.claims', COALESCE(_previous_claims, ''), true);
    PERFORM set_config('request.jwt.claim.sub', COALESCE(_previous_claim_sub, ''), true);
  END IF;

  -- ADR-0015: return the collected stale-write conflicts. Empty under last-write-wins (or when no
  -- write was stale), so the handler simply acks everything as today.
  RETURN QUERY
  SELECT
    (c->>'mutationId')::uuid,
    c->>'tableName',
    (c->>'currentServerVersion')::bigint
  FROM jsonb_array_elements(v_conflicts) AS c;
END;
$$;
