-- Generated by scripts/generate-sync-function-artifact.ts
-- Source of truth: packages/demo/src/registry.ts + packages/server/src/mutations/bulk/plpgsql-strategy.ts

CREATE OR REPLACE FUNCTION pgxsinkit_apply_batch_mutations(
  p_batch jsonb,
  p_request_path text,
  p_log_enabled boolean,
  p_rls_enabled boolean,
  p_user_claims jsonb
) RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  mutation jsonb;
  dml_sql text;
  v_table text;
  v_kind text;
  v_payload jsonb;
  v_entity_key jsonb;
  v_mutation_id text;
  v_mutation_seq integer;
  v_client_timestamp_us bigint;
BEGIN
  IF p_rls_enabled THEN
    PERFORM auth.set_auth_context(COALESCE(p_user_claims, '{}'::jsonb));
  END IF;

  IF jsonb_typeof(p_batch) <> 'object' THEN
    RAISE EXCEPTION 'Batch payload must be a JSON object';
  END IF;

  IF jsonb_typeof(p_batch->'mutations') <> 'array' THEN
    RAISE EXCEPTION 'Batch payload mutations must be a JSON array';
  END IF;

  FOR mutation IN SELECT value FROM jsonb_array_elements(p_batch->'mutations')
  LOOP
    dml_sql := NULL;
    v_table := mutation->>'tableName';
    v_kind := mutation->>'kind';
    v_payload := COALESCE(mutation->'payload', '{}'::jsonb);
    v_entity_key := COALESCE(mutation->'entityKey', '{}'::jsonb);
    v_mutation_id := mutation->>'mutationId';
    v_mutation_seq := (mutation->>'mutationSeq')::integer;
    v_client_timestamp_us := NULLIF(mutation->>'clientTimestampUs', '')::bigint;

    IF FALSE THEN
      NULL;
    ELSIF v_table = 'authors' THEN
        IF v_kind = 'create' THEN
          SELECT format(
          'INSERT INTO "authors" (%s) VALUES (%s)',
          concat_ws(', ', nullif(string_agg(quote_ident(col_name), ', '), ''), '"owner_id", "modified_by", "created_at_us", "updated_at_us"'),
          concat_ws(', ', nullif(string_agg(format('($1->>%L)::%s', col_name, col_type), ', '), ''), 'auth.uid(), auth.uid(), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)')
        )
        INTO dml_sql
        FROM (VALUES
            ('id', 'uuid'),
            ('name', 'varchar')
        ) AS col_types(col_name, col_type)
        WHERE v_payload ? col_name;

        IF dml_sql IS NOT NULL THEN
          EXECUTE dml_sql USING v_payload;
        END IF;
        ELSIF v_kind = 'update' THEN
          SELECT format(
          'UPDATE "authors" SET %s WHERE "id" = ($2->>%L)::uuid',
          concat_ws(', ', nullif(string_agg(format('%I = ($1->>%L)::%s', col_name, col_name, col_type), ', '), ''), '"modified_by" = auth.uid(), "updated_at_us" = CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)'),
          'id'
        )
        INTO dml_sql
        FROM (VALUES
            ('name', 'varchar'),
            ('owner_id', 'uuid'),
            ('created_at_us', 'bigint')
        ) AS col_types(col_name, col_type)
        WHERE v_payload ? col_name;

        IF dml_sql IS NOT NULL THEN
          EXECUTE dml_sql USING v_payload, v_entity_key;
        END IF;
        ELSIF v_kind = 'delete' THEN
          DELETE FROM "authors"
        WHERE "id" = (v_entity_key->>'id')::uuid;
        ELSE
          RAISE EXCEPTION 'Unsupported mutation kind "%" for table "%"', v_kind, v_table;
        END IF;
ELSIF v_table = 'todos' THEN
        IF v_kind = 'create' THEN
          SELECT format(
          'INSERT INTO "todos" (%s) VALUES (%s)',
          concat_ws(', ', nullif(string_agg(quote_ident(col_name), ', '), ''), '"owner_id", "modified_by", "created_at_us", "updated_at_us"'),
          concat_ws(', ', nullif(string_agg(format('($1->>%L)::%s', col_name, col_type), ', '), ''), 'auth.uid(), auth.uid(), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT), CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)')
        )
        INTO dml_sql
        FROM (VALUES
            ('id', 'uuid'),
            ('title', 'varchar'),
            ('description', 'text'),
            ('author_id', 'uuid'),
            ('status', 'varchar'),
            ('priority', 'varchar')
        ) AS col_types(col_name, col_type)
        WHERE v_payload ? col_name;

        IF dml_sql IS NOT NULL THEN
          EXECUTE dml_sql USING v_payload;
        END IF;
        ELSIF v_kind = 'update' THEN
          SELECT format(
          'UPDATE "todos" SET %s WHERE "id" = ($2->>%L)::uuid',
          concat_ws(', ', nullif(string_agg(format('%I = ($1->>%L)::%s', col_name, col_name, col_type), ', '), ''), '"modified_by" = auth.uid(), "updated_at_us" = CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)'),
          'id'
        )
        INTO dml_sql
        FROM (VALUES
            ('title', 'varchar'),
            ('description', 'text'),
            ('author_id', 'uuid'),
            ('owner_id', 'uuid'),
            ('status', 'varchar'),
            ('priority', 'varchar'),
            ('created_at_us', 'bigint')
        ) AS col_types(col_name, col_type)
        WHERE v_payload ? col_name;

        IF dml_sql IS NOT NULL THEN
          EXECUTE dml_sql USING v_payload, v_entity_key;
        END IF;
        ELSIF v_kind = 'delete' THEN
          DELETE FROM "todos"
        WHERE "id" = (v_entity_key->>'id')::uuid;
        ELSE
          RAISE EXCEPTION 'Unsupported mutation kind "%" for table "%"', v_kind, v_table;
        END IF;
    ELSE
      RAISE EXCEPTION 'Unknown table "%" in batch mutation', v_table;
    END IF;

    IF p_log_enabled THEN
      INSERT INTO operations_log (
        source,
        backend,
        table_name,
        operation_kind,
        entity_key_json,
        payload_json,
        status,
        http_status,
        mutation_id,
        mutation_seq,
        client_timestamp_us,
        request_path,
        server_timestamp_us
      ) VALUES (
        'batch',
        'bulk-plpgsql',
        v_table,
        v_kind,
        v_entity_key,
        v_payload,
        'succeeded',
        200,
        v_mutation_id::uuid,
        v_mutation_seq,
        v_client_timestamp_us,
        p_request_path,
        CAST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000000) AS BIGINT)
      );
    END IF;
  END LOOP;
END;
$$;
