-- Generated by pgxsinkit-generate --events
-- Re-run after adding or removing an Event stream.

-- pgxsinkit:events:fp1:3912d95e6ce18520
-- The pgxsinkit event lane's queues (ADR-0053 decision 5): one pgmq queue per registered Event stream.
-- Provisioning is DEPLOY-TIME: the ingestion endpoint may enqueue long before any consumer runner starts.
-- No CASCADE: pgmq's control file declares no `requires`. pgmq is non-relocatable (schema = 'pgmq').
-- pgmq.create() is idempotent (IF NOT EXISTS tables/indexes + ON CONFLICT DO NOTHING meta), so
-- re-applying this migration is a no-op and adding a stream only appends a line.
CREATE EXTENSION IF NOT EXISTS pgmq;
SELECT pgmq.create('pgxsinkit_events_board_issue_viewed');
