import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { demoSyncRegistry } from "@pgxsinkit/demo";

import { buildPlpgsqlBatchFunctionDdl } from "../packages/server/src/mutations/bulk/plpgsql-strategy";

const DEFAULT_OUTPUT_PATH = "infra/sql/functions/pgxsinkit_apply_batch_mutations.sql";

function parseOutputPath(argv: string[]): string {
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index]!;

    if (argument === "--out") {
      return argv[index + 1] ?? DEFAULT_OUTPUT_PATH;
    }

    if (argument.startsWith("--out=")) {
      return argument.slice("--out=".length);
    }
  }

  return DEFAULT_OUTPUT_PATH;
}

async function main() {
  const outputPath = parseOutputPath(process.argv.slice(2));
  const ddl = buildPlpgsqlBatchFunctionDdl(demoSyncRegistry);
  const artifact = `-- Generated by scripts/generate-sync-function-artifact.ts\n-- Source of truth: packages/demo/src/registry.ts + packages/server/src/mutations/bulk/plpgsql-strategy.ts\n\n${ddl}\n`;

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, artifact, "utf8");

  console.log(`Wrote sync function artifact: ${outputPath}`);
}

await main();
