#!/usr/bin/env bun
/**
 * Generates a proper drizzle-kit migration containing the
 * pgxsinkit_apply_batch_mutations PL/pgSQL function.
 *
 * Steps:
 *   1. Runs `drizzle-kit generate --custom --name sync_artifact` to create
 *      an empty, tracked migration directory under infra/drizzle/.
 *   2. Fills the generated migration.sql with the sync function DDL.
 *
 * Usage:
 *   bun scripts/generate-sync-function-artifact.ts                # full migration
 *   bun scripts/generate-sync-function-artifact.ts --stdout        # DDL to stdout only
 */

import { spawnSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { demoSyncRegistry } from "@pgxsinkit/schema";

import { buildPlpgsqlBatchFunctionDdl } from "../packages/server/src/mutations/bulk/plpgsql-strategy";

const MIGRATION_NAME = "sync_artifact";
const DRIZZLE_OUT = "infra/drizzle";

const args = process.argv.slice(2);
const stdout = args.includes("--stdout");
const overrideName = args.find((a) => a.startsWith("--name="));
const name = overrideName ? (overrideName.split("=")[1] ?? MIGRATION_NAME) : MIGRATION_NAME;

// Generate the DDL
const ddl = buildPlpgsqlBatchFunctionDdl(demoSyncRegistry);

if (stdout) {
  console.log(ddl);
  process.exit(0);
}

// Step 1: create empty migration via drizzle-kit
console.log(`Creating empty migration "${name}"...`);
const result = spawnSync(
  "bun",
  ["run", "drizzle-kit", "generate", "--custom", "--name", name, "--config=infra/drizzle.config.ts"],
  {
    cwd: process.cwd(),
    stdio: "inherit",
    env: { ...process.env },
  },
);

if (result.status !== 0) {
  process.exit(result.status ?? 1);
}

// Step 2: find the newly created migration and fill it
const drizzleDir = join(process.cwd(), DRIZZLE_OUT);
const dirs = readdirSync(drizzleDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort()
  .reverse();

for (const dir of dirs) {
  const sqlFile = join(drizzleDir, dir, "migration.sql");
  try {
    const content = readFileSync(sqlFile, "utf-8");
    // The freshly generated custom migration has a short comment-only template
    if (content.length < 100 && content.includes("Custom SQL")) {
      const header = "-- Generated by scripts/generate-sync-function-artifact.ts\n\n";
      writeFileSync(sqlFile, header + ddl + "\n");
      console.log(`Wrote sync function to ${DRIZZLE_OUT}/${dir}/migration.sql`);
      process.exit(0);
    }
  } catch {
    // migration.sql may not exist
  }
}

console.error("Could not find the newly created custom migration in infra/drizzle/. Check drizzle-kit output.");
process.exit(1);
