import { spawnSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { buildRegistryGovernanceSql, governanceSyncRegistry } from "@pgxsinkit/schema";

const DEFAULT_MIGRATION_NAME = "registry_governance";
const DRIZZLE_CONFIG = "infra/drizzle.config.ts";
const DRIZZLE_DIR = "infra/drizzle";

function parseArgs(argv: string[]) {
  let migrationName = DEFAULT_MIGRATION_NAME;

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]!;

    if (arg === "--name" && argv[i + 1]) {
      migrationName = argv[i + 1]!;
      i += 1;
    }
  }

  return { migrationName };
}

function runDrizzleGenerate(migrationName: string): void {
  const result = spawnSync(
    "bun",
    ["run", "drizzle-kit", "generate", "--custom", "--name", migrationName, "--config", DRIZZLE_CONFIG],
    {
      cwd: process.cwd(),
      stdio: "inherit",
      env: { ...process.env },
    },
  );

  if (result.status !== 0) {
    throw new Error(`drizzle-kit generate failed with exit code ${result.status ?? 1}`);
  }
}

function findNewMigrationFile(drizzleDir: string): string {
  const dirs = readdirSync(drizzleDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
    .reverse();

  for (const dir of dirs) {
    const sqlFile = join(drizzleDir, dir, "migration.sql");

    try {
      const content = readFileSync(sqlFile, "utf-8");

      if (content.length < 200 && content.includes("Custom SQL migration file")) {
        return sqlFile;
      }
    } catch {
      // Ignore unreadable files while scanning for the newest generated migration.
    }
  }

  throw new Error("Could not find the newly created governance migration file.");
}

async function main() {
  const { migrationName } = parseArgs(process.argv.slice(2));
  const ddl = buildRegistryGovernanceSql(governanceSyncRegistry).trim();

  if (ddl.length === 0) {
    throw new Error("Typed governance registry did not produce any SQL.");
  }

  runDrizzleGenerate(migrationName);

  const migrationFile = findNewMigrationFile(join(process.cwd(), DRIZZLE_DIR));
  const header =
    "-- Generated by scripts/generate-governance-migration.ts\n-- Re-run after registry governance changes.\n\n";

  writeFileSync(migrationFile, `${header}${ddl}\n`);
  console.log(`Wrote governance migration to ${migrationFile}`);
}

await main();
