ALTER POLICY "channel_select" ON "channel" TO "authenticated" USING ((("channel"."kind" = 'global') or ("channel"."team_id" in (select board_member_team_ids())) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'))));--> statement-breakpoint
ALTER POLICY "issue_select" ON "issue" TO "authenticated" USING ((("issue"."team_id" in (select board_member_team_ids())) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'))));--> statement-breakpoint
ALTER POLICY "issue_insert" ON "issue" TO "authenticated" WITH CHECK ((("issue"."team_id" in (select board_member_team_ids())) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'))));--> statement-breakpoint
ALTER POLICY "issue_update" ON "issue" TO "authenticated" USING ((("issue"."team_id" in (select board_member_team_ids())) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin')))) WITH CHECK ((("issue"."team_id" in (select board_member_team_ids())) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'))));--> statement-breakpoint
ALTER POLICY "issue_delete" ON "issue" TO "authenticated" USING ((("issue"."team_id" in (select board_member_team_ids())) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'))));--> statement-breakpoint
ALTER POLICY "message_select" ON "message" TO "authenticated" USING ((("message"."channel_id" in (select "channel"."id" from "channel" where (("channel"."kind" = 'global') or ("channel"."team_id" in (select board_member_team_ids()))))) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'))));--> statement-breakpoint
ALTER POLICY "message_insert" ON "message" TO "authenticated" WITH CHECK ((("message"."channel_id" in (select "channel"."id" from "channel" where (("channel"."kind" = 'global') or ("channel"."team_id" in (select board_member_team_ids()))))) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'))));--> statement-breakpoint
ALTER POLICY "message_update" ON "message" TO "authenticated" USING ((("message"."author_id" = auth.uid()) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin')))) WITH CHECK ((("message"."author_id" = auth.uid()) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'))));--> statement-breakpoint
ALTER POLICY "message_delete" ON "message" TO "authenticated" USING ((("message"."author_id" = auth.uid()) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'))));--> statement-breakpoint
ALTER POLICY "profile_select" ON "profile" TO "authenticated" USING ((auth.uid() is not null));--> statement-breakpoint
ALTER POLICY "team_member_select" ON "team_member" TO "authenticated" USING ((("team_member"."team_id" in (select board_member_team_ids())) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'))));--> statement-breakpoint
ALTER POLICY "team_select" ON "team" TO "authenticated" USING ((("team"."id" in (select board_member_team_ids())) or (EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'))));