#!/usr/bin/env bun
/**
 * pgxsinkit-generate — Generates a drizzle-kit migration with the
 * pgxsinkit_apply_mutations PL/pgSQL function.
 *
 * External consumers (e.g. transcrobes) invoke this from their own project:
 *
 *   bun run pgxsinkit-generate \
 *     --registry packages/lib/src/sync-registry/index.ts \
 *     --project-dir packages/db \
 *     --name sync_artifact
 *
 * This runs `drizzle-kit generate --custom --name <name>` in --project-dir,
 * then fills the new migration.sql with the generated DDL.
 * The result is a standard drizzle-kit migration tracked via snapshot.json.
 */

import { spawnSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { SyncTableRegistry } from "@pgxsinkit/contracts";

import { buildPlpgsqlBatchFunctionDdl } from "../mutations/plpgsql-apply";

function parseArgs(argv: string[]) {
  let registryPath = "";
  let projectDir = process.cwd();
  let migrationName = "sync_artifact";
  let drizzleConfig = "";

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]!;
    if (arg === "--registry" && argv[i + 1]) {
      registryPath = argv[++i]!;
    } else if (arg === "--project-dir" && argv[i + 1]) {
      projectDir = argv[++i]!;
    } else if (arg === "--name" && argv[i + 1]) {
      migrationName = argv[++i]!;
    } else if (arg === "--config" && argv[i + 1]) {
      drizzleConfig = argv[++i]!;
    }
  }

  if (!registryPath) {
    console.error(
      "Usage: pgxsinkit-generate --registry <path> [--project-dir .] [--name sync_artifact] [--config drizzle.config.ts]",
    );
    process.exit(1);
  }

  return { registryPath, projectDir, migrationName, drizzleConfig };
}

async function importRegistry(registryPath: string, projectDir: string): Promise<SyncTableRegistry> {
  // Resolve relative to the project directory (which is cwd when running from project root)
  const absProjectDir = join(process.cwd(), projectDir);
  const resolved = registryPath.startsWith("/") ? registryPath : join(absProjectDir, registryPath);
  const mod = await import(resolved.startsWith("file://") ? resolved : `file://${resolved}`);
  return mod.transcrobesSyncRegistry ?? mod.demoSyncRegistry ?? mod.default;
}

function runDrizzleGenerate(projectDir: string, name: string, drizzleConfig?: string): void {
  const cwd = join(process.cwd(), projectDir);
  const args = ["run", "drizzle-kit", "generate", "--custom", "--name", name];
  if (drizzleConfig) args.push("--config", drizzleConfig);
  const result = spawnSync("bun", args, {
    cwd,
    stdio: "inherit",
    env: { ...process.env },
  });

  if (result.status !== 0) {
    throw new Error(`drizzle-kit generate failed with exit code ${result.status ?? 1}`);
  }
}

function findDrizzleDir(projectDir: string): string | null {
  const cwd = join(process.cwd(), projectDir);
  for (const name of ["drizzle", "infra/drizzle"]) {
    const full = join(cwd, name);
    try {
      if (readdirSync(full).length > 0) return full;
    } catch {}
  }
  return null;
}

function findNewMigrationFile(drizzleDir: string): string | null {
  const dirs = readdirSync(drizzleDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()
    .reverse();

  for (const dir of dirs) {
    const sqlFile = join(drizzleDir, dir, "migration.sql");
    try {
      const content = readFileSync(sqlFile, "utf-8");
      if (content.length < 100 && content.includes("Custom SQL")) {
        return sqlFile;
      }
    } catch {}
  }

  return null;
}

async function main() {
  const { registryPath, projectDir, migrationName, drizzleConfig } = parseArgs(process.argv.slice(2));

  console.log(`Importing registry from ${registryPath}...`);
  const registry = await importRegistry(registryPath, projectDir);

  console.log(`Generating DDL for ${Object.keys(registry).length} table(s)...`);
  const ddl = buildPlpgsqlBatchFunctionDdl(registry);

  console.log(`Creating empty migration via drizzle-kit generate --custom --name ${migrationName}...`);
  runDrizzleGenerate(projectDir, migrationName, drizzleConfig);

  const drizzleDir = findDrizzleDir(projectDir);
  if (!drizzleDir) {
    console.error("Could not find drizzle output directory in", projectDir);
    process.exit(1);
  }

  const migrationFile = findNewMigrationFile(drizzleDir);
  if (!migrationFile) {
    console.error("Could not find the newly created migration file.");
    process.exit(1);
  }

  const header = "-- Generated by pgxsinkit-generate\n-- Re-run after any registry change.\n\n";
  writeFileSync(migrationFile, header + ddl + "\n");
  console.log(`Wrote sync function to ${drizzleDir}/.../migration.sql`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
