// Began as a copy of `@electric-sql/pglite`'s tests (taken under its PostgreSQL License option,
// © ElectricSQL — see NOTICE). Owned outright (ADR-0062); compatibility with PGlite is an anti-goal.

import { afterEach, describe, expect, it } from "bun:test";

import { closeTestPgwasms, createTestPgwasm } from "./support/pgwasm";

// Replies of every size pass through the exchange's chunk collection and the parser. The sizes are
// trimmed from the ones this began with (up to 128 MB values, 1 GB results) to what the unit lane can
// run in its time budget while still crossing several collection-buffer growths.

afterEach(closeTestPgwasms);

const sizes: Record<string, number> = { "8kb": 8 * 1024, "5mb": 5 * 1024 * 1024, "12mb": 12 * 1024 * 1024 };
const rowShapes: [label: string, rows: number, bytes: number][] = [
  ["1k rows of 1kb", 1000, 1024],
  ["10k rows of 100b", 10000, 100],
  ["10k rows of 10kb", 10000, 10 * 1024],
];

async function withTable() {
  const db = await createTestPgwasm();
  await db.exec("CREATE TABLE IF NOT EXISTS size_test (id SERIAL PRIMARY KEY, data TEXT);");
  return db;
}

describe("values of different sizes", () => {
  for (const [label, size] of Object.entries(sizes)) {
    it(`round-trips ${label} through exec`, async () => {
      const db = await withTable();
      const data = "a".repeat(size);
      const results = await db.exec(`INSERT INTO size_test (data) VALUES ('${data}'); SELECT * FROM size_test;`);
      expect(results).toHaveLength(2);
      const row = results[1]?.rows[0] as { data: string } | undefined;
      expect(row?.data.length).toBe(size);
      expect(row?.data).toBe(data);
    });

    it(`round-trips ${label} through query, as a literal and as a parameter`, async () => {
      const db = await withTable();
      const data = "a".repeat(size);
      await db.query(`INSERT INTO size_test (data) VALUES ('${data}');`);
      await db.query("INSERT INTO size_test (data) VALUES ($1);", [data]);
      const result = await db.query<{ data: string }>("SELECT * FROM size_test WHERE data = $1;", [data]);
      expect(result.rows).toHaveLength(2);
      expect(result.rows[1]?.data).toBe(data);
    });

    it(`reads ${label} generated by Postgres`, async () => {
      const db = await createTestPgwasm();
      const result = await db.query<{ data: string }>(`SELECT 1 as id, repeat('a', ${size}) as data;`);
      expect(result.rows[0]?.data.length).toBe(size);
    });
  }
});

describe("results of different row counts", () => {
  for (const [label, rowCount, size] of rowShapes) {
    it(`reads ${label}`, async () => {
      const db = await createTestPgwasm();
      const data = "a".repeat(size);
      const result = await db.query<{ id: number; data: string }>(
        `SELECT generate_series(1, ${rowCount}) as id, '${data}' as data;`,
      );
      expect(result.rows).toHaveLength(rowCount);
      for (const index of [0, Math.floor(rowCount / 2), rowCount - 1]) {
        expect(result.rows[index]?.data).toBe(data);
      }
    });
  }
});
