-- Generated by scripts/generate-governance-migration.ts
-- Registry source: packages/demo/src/registry.ts

-- Source: registry.todos.governance.deferrableConstraints.todos_author_id_authors_id_fkey
ALTER TABLE "todos"
ALTER CONSTRAINT "todos_author_id_authors_id_fkey"
DEFERRABLE INITIALLY IMMEDIATE;
